#!/bin/bash

if [ $# -ne 1 ]; then
	echo -e "\nUsage: viewpng [ang directory number]"
	echo " - downloads and opens the spectrum png directory for the given angle grid position"
	echo ""
	exit
fi

remotedir=$1
localdir="${remotedir##*/}/"

if [ -e $localdir ]; then
	rm $localdir*.png
else
	mkdir $localdir
fi

scp -r "thalia:$remotedir/*" $localdir
open $localdir/*

printf "\a"
